version: "3"
services:
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./env/server.env
    container_name: server
    networks:
      default:

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      # - /workspaces/CoderHub/client:/client
      # - /workspaces/CoderHub/client/build:/client/build
      - node_modules:/client/node_modules
    stdin_open: true
    tty: true
    container_name: client
    depends_on:
      - backend
    networks:
      default:

networks:
  default:

volumes:
  node_modules:
