apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: kishothkumar/coderzhub-client
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"