apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: kishothkumar/coderzhub-server
        resources:
          # limits:
            # memory: "128Mi"
            # cpu: "500m"